# site settings
title: UniFit Consultancy
subtitle: UniFit Consultancy Services
email: unifitconsultancy@gmail.com
description: UniFit Consultancy Services
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Kedgaon
city: Ahmednagar
state: MH
zip_code: 414003
country: India
phone: +91-8888488548

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  # GitHub: https://github.com/andrewbanchich
  # GitLab:
  # Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  # Instagram:
  # LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  # Twitter: https://twitter.com/andrewbanchich
  # Facebook:
  # Slack:
  WhatsApp: +91-8888488548

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
